totalWidth: 1248
totalHeight: 192
windowHeight: 216
targetWidth: 80
targetHeight: 48
sleepTime: 1000
scale: 2
commendText: |
  文字清晰度评分
  1: 非常不清晰
  
  2: 不清晰
  
  3: 有点不清晰
  
  4: 一般
  
  5: 有点清晰
  
  6: 清晰
  
  7: 非常清晰
commentHint: 按1-7数字键选择
textExamTitle: 文字搜索实验
textExamContent: |
  接下来你将完成若干次文字搜索任务。每次
  
  任务开始前，我们会为你呈现目标词，你需要在
  
  下一屏找到这个目标词，尽量又快又准确地完成
  
  每次任务。目标词在屏幕上的位置会发生变化，
  
  请仔细观察。如果有疑问，请随时联系实验员。
numExamTitle: 数字识别实验
numExamContent: |
  接下来你将完成若干次数字识别任务，每屏 会为你呈现一个数字，
  
  你需要判断数字是否大于 600，尽量又快又准确地完成每次任务。
  
  数字在 屏幕上的位置会发生变化，请仔细观察。如果有 疑问，
  
  请随时联系实验员。
disName: ["3m", "5m", "7m"]
fontSize: [6, 12]
keyMap:
  1: 0
  2: 1
  3: 2
  4: 3
  5: 4
  6: 5
  7: 6
  8: 7
  9: 8
textSize: 12
repeatTimes: 2
